FROM registry.svc.ci.openshift.org/openshift/release:golang-1.12 AS registry_image 

WORKDIR /tmp/kubevirt
COPY . .

FROM kubevirt/builder@sha256:7585e27b5a5a019f5749eaa1ef29da3278878eefc862b45d6e1c2e343d9f8859 AS builder
COPY --from=registry_image /tmp/kubevirt /go/src/kubevirt.io/kubevirt
RUN chmod -R 777 /go/src/kubevirt.io/kubevirt
COPY --from=registry_image /tmp/kubevirt/hack/builder/rsyncd.conf /etc/rsyncd.conf

WORKDIR /go/src/kubevirt.io/kubevirt

RUN \
    export DOCKER_PREFIX='dhiller' && \
    export DOCKER_TAG="latest" && \
    export KUBEVIRT_PROVIDER=external && \
    export GIMME_GO_VERSION=1.12.8 && \
    export GOPATH="/go" && \
    export GOBIN="/usr/bin" && \
    source /etc/profile.d/gimme.sh && \
    bash -x ./hack/build-manifests.sh && \
    export CMD_OUT_DIR="$(pwd)/_out/cmd" && \
    mkdir -p _out/cmd/dump/ && \
    GOPROXY=off GOFLAGS=-mod=vendor go build -o "$CMD_OUT_DIR/dump/dump" ./cmd/dump && \
    bash -x ./hack/build-func-tests.sh

ENV GIMME_GO_VERSION=1.12.8
ENV GOPATH="/go" GOBIN="/usr/bin"
ENV PATH="$PATH:/usr/local/go/bin/"
